apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: one-api-backend
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Garinlu/one-api-infra.git
    targetRevision: main
    path: gitops
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true